### PR TITLE
Build environment + support for WS2812 LEDs + bug fix + small enhancements

### PR DESCRIPTION
**Pull request by rdmrocha**
Heavily inspired by https://github.com/shalxmva/modxo/pull/23

- refactored the LED access to be able to support custom boards
- adds support for WS2812 LEDs (most commonly found on cheap RP2040 Zero boards)
- bin2uf2:
  - fixes bug in header address mask (@shalxmva lots of formatting and style changes so the linter can shut up, the only critical patch is inside `get_uf2_romaddr_mask_block` where we adjust the header block address correctly. It matches go and https://shalxmva.github.io/modxo/ outputs)
  - adds input file glob support
  - adds support for output folder
- added docker builder based on the work from @dferramosi in https://github.com/shalxmva/modxo/pull/23
- improvements to the cmake files and include paths

### CODE REVIEW

**Comment by dferramosi** [comment]
This looks great! I'm glad my work was able to last the foundation for an even better setup!

**Comment by shalxmva** [comment]
I am just going to take a look, i was on vacation.
Is this independant on what @dferramosi did?
Or do i need to merge first his change?

**Comment by rdmrocha** [comment]
Independent. It's basically a cherry-pick from his PR with enhancements and fixes

**Comment by shalxmva** [comment]
Thanks!!!

**Pull request merged**
